### PR TITLE
Add Feature: Multidiffusion

### PR DESCRIPTION
**Pull request by Isotr0py**
- Add another super resolution image generator: Multidiffusion
- Same to [multidiffusion in auto1111](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) and [panorama in `diffusers`](https://huggingface.co/docs/diffusers/v0.16.0/en/api/pipelines/stable_diffusion/panorama#available-pipelines). Modified to support all schedulers.

Available in diffusers mode. Still in test for TensorRT.

### CODE REVIEW

**Comment by Isotr0py** [comment]
It works in tensorrt! Creating a 2048*512 panorama image costs only about 1min in tensorrt!
2-1191763617-skyline

**Comment by ddPn08** [comment]
wonderful!
I'm not very familiar with multi diffusion, but does this mean I can exceed the maximum resolution of the tensorrt engine?

**Comment by Isotr0py** [comment]
@ddPn08 Yes. The maximum resolution of the tensorrt engine only limit the tile size of multi-diffusion, image resolution won't be limited.

**Comment by ddPn08** [comment]
> @ddPn08 Yes. The maximum resolution of the tensorrt engine only limit the tile size of multi-diffusion (here I set it to 512*512), image resolution won't be limited.

thank you. This is really awesome.
It didn't work well with euler a, but it worked fine with ddim.
Is this normal?

**Comment by ddPn08** [comment]
I tried again with euler and it worked. Some samplers may not work well.
It is probably a specification, so I will merge it as it is

**Comment by Isotr0py** [comment]
I think ancestral samplers like `euler_a` and `dpm2-a` are specifications that unsuitable for multi-diffusion, because they will add random noise to each tiles in each timestep.

**Comment by Isotr0py** [comment]
Emmm, I tested [multidiffusion in auto1111](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) with `euler_a` and it can generate image normally. Maybe something went wrong for ancestral schedulers🤔

**Comment by Isotr0py** [comment]
OK, moving the noise adding outside the tile loop can solve the ancestral sampler problem.  It means that we need to refactor `euler_a` and `dpm2-a` sampler...

**Comment by Isotr0py** [comment]
By hijacking ancestral schedulers, `euler_a` and `dpm2-a` should work in multi-diffusion now.

**Review by ddPn08 — APPROVED** [review]

**Pull request merged**
